# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('vanue', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=6)),
                ('address_1', models.CharField(max_length=80)),
                ('address_2', models.CharField(max_length=80)),
                ('address_city', models.CharField(max_length=80)),
                ('address_state_province', models.CharField(max_length=80)),
                ('address_postal_code', models.CharField(max_length=80)),
                ('address_country', django_countries.fields.CountryField(max_length=2)),
                ('home_airport', models.CharField(max_length=4)),
                ('display_name', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(to='wedding.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rsvp_status', models.IntegerField(choices=[(1, 'No Response'), (2, 'Attending'), (3, 'Not attending')], default=1)),
                ('name_flagged', models.BooleanField()),
                ('dietary_restrictions', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Group')),
            ],
        ),
    ]
