# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20170508_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(blank=True, to='wedding.Event'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
    ]
