# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_auto_20170508_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_state_province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='home_airport',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
