# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_auto_20170508_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('plain_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Mailout')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Person')),
            ],
        ),
    ]
