# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_mailout_mailsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailout',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wedding.Event'),
            preserve_default=False,
        ),
    ]
