# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_mailout_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsent',
            name='datestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
