# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_mailsent_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(default='', help_text='This is used to look up an event, e.g. by the group_has_event tag.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='address_1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='City or suburb'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_state_province',
            field=models.CharField(blank=True, max_length=80, verbose_name='State or Province'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=models.CharField(max_length=6, unique=True, verbose_name='Confirmation code'),
        ),
    ]
