# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20170527_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_name',
            field=models.CharField(help_text='This is used to look up an event, e.g. by the group_has_event tag.', max_length=20, unique=True),
        ),
    ]
