# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wedding', '0011_auto_20170527_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address_1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='group',
            name='address_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='City or Suburb'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=models.CharField(max_length=6, unique=True, verbose_name='Confirmation Code'),
        ),
    ]
