# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('wedding', '0012_auto_20170528_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
