# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wedding', '0014_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='directions_url',
            field=models.CharField(default='https://www.google.com/maps/?q=', max_length=255),
            preserve_default=False,
        ),
    ]
